// Merges an additional batch of validated Hebrew 5-letter words into
// public/words.json. Companion to build_words.py, and applies the same rules
// CLAUDE.md requires for any word-bank expansion:
//
//   * exact 5-letter length, by HEBREW_LETTERS set membership (not .length,
//     which would silently accept niqqud or stray punctuation)
//   * no final-form letter (ך/ם/ן/ף/ץ) anywhere but the last position — that
//     is the signature of the naive-concatenation bug described in CLAUDE.md
//   * no duplicates, including duplicates that collide only after final-letter
//     normalization (ך→כ etc.), since those are indistinguishable in play
//   * every rejection is printed, never silently dropped
//
// These words were written out individually, NOT generated by appending
// ות/ים to roots. That approach is explicitly banned in CLAUDE.md because it
// produces non-words like אבןות.
//
// Usage: node build_words_he_extra.cjs public/words.json

const fs = require("fs");

const HEBREW_LETTERS = new Set("אבגדהוזחטיכלמנסעפצקרשתךםןףץ".split(""));
const FINALS = { ך: "כ", ם: "מ", ן: "נ", ף: "פ", ץ: "צ" };

const ADDITIONS = `
אנשים דגלים חברים מורים מורות תלמיד כיתות שיעור מחברת עפרון טלפון מיטות דלתות
חולצה שמלות צבעים ירוקה צהובה שחורה לבנים עוגות גבינה ביצים ירקות פירות בננות
ענבים אגסים בצלים גזרים מרקים סלטים מיצים הלכתי אמרתי ראיתי שמעתי ידעתי כתבתי
קראתי עשיתי הייתי רציתי חשבתי אהבתי למדתי נסעתי הלכנו אמרנו ראינו שמענו הולכת
כותבת קוראת אוכלת רוצים יכולה צריכה עובדת מדברת חושבת לומדת יושבת עומדת רוקדת
מבינה זוכרת גדולה קטנים טובים חדשים ישנים ארוכה קצרים גבוהה נמוכה חזקים חלשים
מהירה איטית יקרים זולים שמחים עצובה כועסת עייפה שמיים גשמים רוחות עמקים נהרות
יערות פרחים חופים גבעות חולות מדינה עיירה כפרים שכונה בניין דירות חדרים מרפסת
גינות תחנות נמלים גשרים מסלול ערבים לילות רגעים עונות ראשים ידיים לבבות סיפור
שירים תמונה סרטים מתנות כספים עבודה חופשה נסיעה מסעדה רעיון שאלות בעיות פתרון
סיבות מטרות הצלחה חוויה משפחה הורים דודים נכדים תינוק גברים טבחים נהגים ילדות
`;

const target = process.argv[2];
if (!target) {
  console.error("usage: node build_words_he_extra.cjs <path-to-words.json>");
  process.exit(1);
}

const existing = JSON.parse(fs.readFileSync(target, "utf8"));

function normalize(word) {
  return [...word].map((c) => FINALS[c] || c).join("");
}

const seenNormalized = new Set(existing.map((o) => normalize(o.word)));
const rejected = [];
const accepted = [];

for (const raw of ADDITIONS.trim().split(/\s+/).filter(Boolean)) {
  const chars = [...raw];

  if (chars.length !== 5) {
    rejected.push([raw, `length ${chars.length}, expected 5`]);
    continue;
  }
  if (!chars.every((c) => HEBREW_LETTERS.has(c))) {
    rejected.push([raw, "contains a non-Hebrew-letter character"]);
    continue;
  }
  const misplacedFinal = chars.slice(0, 4).find((c) => FINALS[c]);
  if (misplacedFinal) {
    rejected.push([raw, `final letter ${misplacedFinal} in a non-final position`]);
    continue;
  }
  if (FINALS[chars[4]] === undefined && "כמנפצ".includes(chars[4])) {
    rejected.push([raw, `ends in medial ${chars[4]}, expected its final form`]);
    continue;
  }
  const norm = normalize(raw);
  if (seenNormalized.has(norm)) {
    rejected.push([raw, "duplicate (already in bank, after normalization)"]);
    continue;
  }

  seenNormalized.add(norm);
  accepted.push({ word: raw, common: true });
}

const merged = [...existing, ...accepted].sort((a, b) =>
  a.word.localeCompare(b.word, "he")
);

const body = merged
  .map((o) => `{\n"word": "${o.word}",\n"common": ${o.common}\n}`)
  .join(",\n");

fs.writeFileSync(target, `[\n${body}\n]\n`, "utf8");

console.log(`bank was:  ${existing.length}`);
console.log(`accepted:  ${accepted.length}`);
console.log(`rejected:  ${rejected.length}`);
for (const [w, why] of rejected) console.log(`   ${w} — ${why}`);
console.log(`bank now:  ${merged.length}`);
